from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from lab_sidecar.reports.service import (
    MAX_DISPLAY_COLUMNS,
    MAX_NUMERIC_SUMMARY_COLUMNS,
    STDERR_TAIL_LINES,
)
from tests.test_cli_smoke import copy_examples, extract_task_id, invoke, wait_for_output


REQUIRED_TOP_LEVEL_KEYS = {
    "schema_version",
    "task_id",
    "template",
    "generated_at",
    "report_path",
    "summary_path",
    "generated_from",
    "provenance",
    "metrics",
    "figures",
    "failure",
    "cancellation",
    "reproduce",
    "claim_traces",
    "source_artifacts",
}
TASK_STATUS_VALUES = {"pending", "running", "completed", "failed", "cancelled"}
REQUIRED_PROVENANCE_KEYS = {
    "task_id",
    "status",
    "mode",
    "command",
    "source_path",
    "working_dir",
    "created_at",
    "started_at",
    "finished_at",
    "exit_code",
}
REQUIRED_METRICS_KEYS = {
    "present",
    "path",
    "collection_summary_path",
    "scenario_summary_path",
    "scenario",
    "row_count",
    "columns",
    "displayed_columns",
    "omitted_column_count",
    "numeric_summaries",
    "numeric_omitted_count",
    "detected_fields",
}
REQUIRED_SCENARIO_KEYS = {
    "present",
    "path",
    "scenario_type",
    "primary_metric",
    "groups",
    "best_rows",
    "last_rows",
    "seed_aggregates",
    "warnings",
    "omitted",
}
REQUIRED_PRIMARY_METRIC_KEYS = {"name", "direction", "unit", "selection_reason"}
REQUIRED_GROUP_KEYS = {"configured", "primary", "secondary", "seed", "context", "inferred"}
REQUIRED_FIGURES_KEYS = {"present", "task_id", "summary_path", "figure_count", "items", "warnings", "errors"}
REQUIRED_FIGURE_ITEM_KEYS = {"figure_id", "chart_type", "png_path", "svg_path", "x", "y", "group_by"}
REQUIRED_FAILURE_KEYS = {"failure_summary", "stderr_tail", "stderr_tail_line_count", "reproduce_command_path"}
REQUIRED_CANCELLATION_KEYS = {"note", "stderr_tail", "stderr_tail_line_count"}
FORBIDDEN_EMBEDDED_FRAGMENTS = (
    "# 实验报告片段",
    "# 失败实验报告片段",
    "# 取消实验报告片段",
    "## 实验概览",
    "## 失败概览",
    "## 取消概览",
    "本报告由确定性模板生成，不使用 AI。",
    "This fragment is generated by deterministic templates and does not use AI.",
    "Best val_accuracy=0.86 at epoch 5",
    "epoch,train_loss,val_loss",
    '"prompt":"secret"',
    '"response":"secret"',
    "ppt/presentation.xml",
)


def read_report_summary(workspace: Path, task_id: str) -> dict[str, Any]:
    path = workspace / ".lab-sidecar" / "tasks" / task_id / "reports" / "report-summary.json"
    return json.loads(path.read_text(encoding="utf-8"))


def assert_report_summary_contract(
    summary: dict[str, Any],
    *,
    workspace: Path,
    expected_task_id: str,
    expected_status: str,
) -> None:
    task_path = workspace / ".lab-sidecar" / "tasks" / expected_task_id
    reports_dir = task_path / "reports"

    assert REQUIRED_TOP_LEVEL_KEYS <= set(summary)
    assert summary["schema_version"] == "1"
    assert summary["task_id"] == expected_task_id
    assert isinstance(summary["template"], str) and summary["template"]
    assert isinstance(summary["generated_at"], str) and summary["generated_at"]
    assert summary["report_path"] == "reports/report-fragment.md"
    assert summary["summary_path"] == "reports/report-summary.json"
    assert (task_path / "reports" / "report-fragment.md").is_file()
    assert (task_path / "reports" / "report-summary.json").is_file()

    _assert_source_artifacts(summary["generated_from"], task_path=task_path)
    _assert_source_artifacts(summary["source_artifacts"], task_path=task_path)
    assert summary["generated_from"] == summary["source_artifacts"]

    _assert_provenance(summary["provenance"], expected_task_id=expected_task_id, expected_status=expected_status)
    _assert_metrics_summary(summary["metrics"], task_path=task_path)
    _assert_figures_summary(summary["figures"], task_path=task_path, reports_dir=reports_dir, expected_task_id=expected_task_id)
    _assert_failure_context(summary["failure"], task_path=task_path)
    _assert_cancellation_context(summary["cancellation"], task_path=task_path)
    _assert_reproduce(summary["reproduce"], task_path=task_path)
    _assert_claim_traces(summary["claim_traces"], summary=summary, expected_status=expected_status)
    _assert_summary_is_reference_only(summary)


def _assert_source_artifacts(items: list[str], *, task_path: Path) -> None:
    assert isinstance(items, list)
    assert items
    assert "reports/report-fragment.md" not in items
    assert "reports/report-summary.json" not in items
    for item in items:
        assert isinstance(item, str) and item and "\n" not in item
        assert (task_path / item).exists()


def _assert_provenance(
    provenance: dict[str, Any],
    *,
    expected_task_id: str,
    expected_status: str,
) -> None:
    assert set(provenance) == REQUIRED_PROVENANCE_KEYS
    assert provenance["task_id"] == expected_task_id
    assert provenance["status"] == expected_status
    assert provenance["status"] in TASK_STATUS_VALUES
    assert provenance["mode"] in {"run", "ingest"}
    for key in ["command", "source_path", "working_dir", "created_at", "started_at", "finished_at"]:
        assert isinstance(provenance[key], str) and provenance[key]
    assert provenance["exit_code"] == "未自动推断" or isinstance(provenance["exit_code"], int)


def _assert_metrics_summary(metrics: dict[str, Any], *, task_path: Path) -> None:
    assert REQUIRED_METRICS_KEYS <= set(metrics)
    assert isinstance(metrics["present"], bool)
    assert metrics["path"] == "metrics/normalized_metrics.csv"
    assert metrics["collection_summary_path"] in {None, "metrics/collection-summary.json"}
    assert metrics["scenario_summary_path"] in {None, "metrics/scenario-summary.json"}

    if metrics["collection_summary_path"] is not None:
        assert (task_path / metrics["collection_summary_path"]).is_file()
    if metrics["scenario_summary_path"] is not None:
        assert (task_path / metrics["scenario_summary_path"]).is_file()

    row_count = metrics["row_count"]
    assert isinstance(row_count, int)
    assert row_count >= 0

    columns = metrics["columns"]
    displayed_columns = metrics["displayed_columns"]
    assert isinstance(columns, list)
    assert all(isinstance(column, str) and column for column in columns)
    assert isinstance(displayed_columns, list)
    assert displayed_columns == columns[:MAX_DISPLAY_COLUMNS]
    assert metrics["omitted_column_count"] == max(0, len(columns) - MAX_DISPLAY_COLUMNS)

    numeric_summaries = metrics["numeric_summaries"]
    assert isinstance(numeric_summaries, list)
    assert len(numeric_summaries) <= MAX_NUMERIC_SUMMARY_COLUMNS
    for item in numeric_summaries:
        _assert_numeric_summary(item, columns=columns, row_count=row_count)
    if metrics["numeric_omitted_count"] > 0:
        assert len(numeric_summaries) == MAX_NUMERIC_SUMMARY_COLUMNS
    else:
        assert len(numeric_summaries) <= MAX_NUMERIC_SUMMARY_COLUMNS
    assert isinstance(metrics["numeric_omitted_count"], int)
    assert metrics["numeric_omitted_count"] >= 0

    detected_fields = metrics["detected_fields"]
    assert isinstance(detected_fields, list)
    assert all(isinstance(field, str) and field for field in detected_fields)
    assert len(detected_fields) == len(set(detected_fields))

    if metrics["present"]:
        assert row_count > 0
        assert (task_path / metrics["path"]).is_file()
        assert columns
        if "candidate_count" in metrics:
            assert isinstance(metrics["candidate_count"], int)
            assert metrics["candidate_count"] >= 0
        if "processed_files" in metrics:
            assert isinstance(metrics["processed_files"], list)
            assert all(isinstance(item, dict) for item in metrics["processed_files"])
    else:
        assert row_count == 0
        assert columns == []
        assert displayed_columns == []
        assert metrics["omitted_column_count"] == 0
        assert numeric_summaries == []
        assert metrics["numeric_omitted_count"] == 0
        assert detected_fields == []

    _assert_compact_scenario(metrics["scenario"])


def _assert_numeric_summary(item: dict[str, Any], *, columns: list[str], row_count: int) -> None:
    assert set(item) == {"column", "count", "mean", "min", "max"}
    assert isinstance(item["column"], str) and item["column"]
    assert item["column"] in columns
    assert isinstance(item["count"], int)
    assert 0 < item["count"] <= row_count
    for key in ["mean", "min", "max"]:
        assert item[key] is None or isinstance(item[key], int | float)


def _assert_compact_scenario(scenario: dict[str, Any]) -> None:
    assert isinstance(scenario, dict)
    if not scenario.get("present"):
        assert scenario == {"present": False}
        return

    assert REQUIRED_SCENARIO_KEYS <= set(scenario)
    assert scenario["path"] == "metrics/scenario-summary.json"
    assert scenario["scenario_type"] in {"training-run", "algorithm-benchmark"}

    primary_metric = scenario["primary_metric"]
    assert set(primary_metric) == REQUIRED_PRIMARY_METRIC_KEYS
    assert primary_metric["name"] is None or isinstance(primary_metric["name"], str)
    assert primary_metric["direction"] in {"max", "min", None}
    assert primary_metric["unit"] is None or _is_bounded_scalar(primary_metric["unit"])
    assert _is_bounded_scalar(primary_metric["selection_reason"])

    groups = scenario["groups"]
    assert set(groups) == REQUIRED_GROUP_KEYS
    assert isinstance(groups["configured"], dict)
    assert groups["primary"] is None or isinstance(groups["primary"], str)
    assert groups["secondary"] is None or isinstance(groups["secondary"], str)
    assert groups["seed"] is None or isinstance(groups["seed"], str)
    assert isinstance(groups["context"], list)
    assert isinstance(groups["inferred"], list)

    best_rows = scenario["best_rows"]
    last_rows = scenario["last_rows"]
    assert isinstance(best_rows, list)
    assert isinstance(last_rows, list)
    assert len(best_rows) <= 3
    assert len(last_rows) <= 3
    for item in best_rows:
        _assert_compact_best_row(item)
    for item in last_rows:
        _assert_compact_last_row(item)

    seed_aggregates = scenario["seed_aggregates"]
    assert isinstance(seed_aggregates["present"], bool)
    assert len(seed_aggregates.get("items", [])) <= 3
    if seed_aggregates["present"]:
        assert isinstance(seed_aggregates["metric"], str) and seed_aggregates["metric"]
        assert seed_aggregates["direction"] in {"max", "min"}
        assert isinstance(seed_aggregates["claim_limit"], str) and seed_aggregates["claim_limit"]
        for item in seed_aggregates["items"]:
            _assert_compact_seed_aggregate(item)
    else:
        assert seed_aggregates["items"] == []

    warnings = scenario["warnings"]
    assert isinstance(warnings, list)
    assert len(warnings) <= 5
    assert all(isinstance(item, str) and item for item in warnings)

    omitted = scenario["omitted"]
    assert isinstance(omitted, dict)
    for value in omitted.values():
        assert value == "omitted_by_default"


def _assert_compact_best_row(item: dict[str, Any]) -> None:
    assert {
        "metric",
        "direction",
        "selection_reason",
        "value",
        "row_number",
        "selected_fields",
        "omitted_field_count",
        "evidence",
    } <= set(item)
    assert isinstance(item["metric"], str) and item["metric"]
    assert item["direction"] in {"max", "min"}
    assert _is_bounded_scalar(item["selection_reason"])
    assert item["value"] is None or isinstance(item["value"], int | float)
    assert isinstance(item["row_number"], int) and item["row_number"] >= 1
    assert isinstance(item["omitted_field_count"], int) and item["omitted_field_count"] >= 0
    _assert_compact_selected_fields(item["selected_fields"])
    _assert_row_evidence(item["evidence"], expected_row_number=item["row_number"])


def _assert_compact_last_row(item: dict[str, Any]) -> None:
    assert {"group", "row_number", "checkpoint_field", "selected_fields", "evidence"} <= set(item)
    assert isinstance(item["group"], dict)
    assert isinstance(item["row_number"], int) and item["row_number"] >= 1
    assert item["checkpoint_field"] is None or isinstance(item["checkpoint_field"], str)
    _assert_compact_selected_fields(item["selected_fields"])
    _assert_row_evidence(item["evidence"], expected_row_number=item["row_number"])


def _assert_compact_seed_aggregate(item: dict[str, Any]) -> None:
    assert {
        "group",
        "metric",
        "direction",
        "row_count",
        "seed_count",
        "mean",
        "min",
        "max",
        "evidence",
    } <= set(item)
    assert isinstance(item["group"], dict)
    assert isinstance(item["metric"], str) and item["metric"]
    assert item["direction"] in {"max", "min"}
    assert isinstance(item["row_count"], int) and item["row_count"] >= 1
    assert isinstance(item["seed_count"], int) and item["seed_count"] >= 1
    for key in ["mean", "min", "max"]:
        assert item[key] is None or isinstance(item[key], int | float)
    evidence = item["evidence"]
    assert evidence["artifact_id"] == "metrics_normalized_csv"
    assert evidence["path"] == "metrics/normalized_metrics.csv"
    assert isinstance(evidence["row_numbers"], list)
    assert len(evidence["row_numbers"]) <= 6
    assert evidence["body"] == "omitted"


def _assert_compact_selected_fields(selected_fields: dict[str, Any]) -> None:
    assert isinstance(selected_fields, dict)
    for key, value in selected_fields.items():
        assert isinstance(key, str) and key
        assert _is_bounded_scalar(value)


def _assert_row_evidence(evidence: dict[str, Any], *, expected_row_number: int) -> None:
    assert evidence == {
        "artifact_id": "metrics_normalized_csv",
        "path": "metrics/normalized_metrics.csv",
        "row_number": expected_row_number,
        "body": "omitted",
    }


def _assert_figures_summary(
    figures: dict[str, Any],
    *,
    task_path: Path,
    reports_dir: Path,
    expected_task_id: str,
) -> None:
    assert set(figures) == REQUIRED_FIGURES_KEYS
    assert figures["task_id"] == expected_task_id
    assert isinstance(figures["present"], bool)
    assert isinstance(figures["figure_count"], int)
    assert figures["figure_count"] >= 0
    assert isinstance(figures["items"], list)
    assert len(figures["items"]) == figures["figure_count"]
    assert isinstance(figures["warnings"], list)
    assert isinstance(figures["errors"], list)
    assert all(isinstance(item, str) and item for item in figures["warnings"])
    assert all(isinstance(item, str) and item for item in figures["errors"])

    if figures["present"]:
        assert figures["summary_path"] == "figures/figure-summary.json"
        assert (task_path / figures["summary_path"]).is_file()
        for item in figures["items"]:
            assert set(item) == REQUIRED_FIGURE_ITEM_KEYS
            assert isinstance(item["figure_id"], str) and item["figure_id"]
            assert isinstance(item["chart_type"], str) and item["chart_type"]
            assert isinstance(item["png_path"], str) and item["png_path"].endswith(".png")
            assert isinstance(item["svg_path"], str) and item["svg_path"].endswith(".svg")
            assert (reports_dir / item["png_path"]).resolve().is_file()
            assert (reports_dir / item["svg_path"]).resolve().is_file()
            assert isinstance(item["x"], str) and item["x"]
            assert isinstance(item["y"], str) and item["y"]
            assert isinstance(item["group_by"], str) and item["group_by"]
    else:
        assert figures["summary_path"] is None
        assert figures["figure_count"] == 0
        assert figures["items"] == []
        assert figures["warnings"] == []
        assert figures["errors"] == []


def _assert_failure_context(failure: dict[str, Any], *, task_path: Path) -> None:
    assert set(failure) == REQUIRED_FAILURE_KEYS
    assert isinstance(failure["failure_summary"], str) and failure["failure_summary"]
    _assert_stderr_tail(failure["stderr_tail"], failure["stderr_tail_line_count"], task_path=task_path)
    assert isinstance(failure["reproduce_command_path"], str) and failure["reproduce_command_path"]
    if failure["reproduce_command_path"] != "未自动推断":
        assert (task_path / failure["reproduce_command_path"]).is_file()


def _assert_cancellation_context(cancellation: dict[str, Any], *, task_path: Path) -> None:
    assert set(cancellation) == REQUIRED_CANCELLATION_KEYS
    assert isinstance(cancellation["note"], str) and cancellation["note"]
    _assert_stderr_tail(cancellation["stderr_tail"], cancellation["stderr_tail_line_count"], task_path=task_path)
    stderr_tail = cancellation["stderr_tail"]
    if stderr_tail:
        assert cancellation["note"] == stderr_tail[-1] or "cancellation" in cancellation["note"].lower()
    else:
        assert cancellation["note"] == "未自动推断"


def _assert_stderr_tail(stderr_tail: list[str], line_count: int, *, task_path: Path) -> None:
    assert isinstance(stderr_tail, list)
    assert isinstance(line_count, int)
    assert line_count == len(stderr_tail)
    assert line_count <= STDERR_TAIL_LINES
    assert all(isinstance(line, str) and "\n" not in line for line in stderr_tail)
    stderr_path = task_path / "stderr.log"
    expected_tail = stderr_path.read_text(encoding="utf-8", errors="replace").splitlines()[-STDERR_TAIL_LINES:]
    assert stderr_tail == expected_tail


def _assert_reproduce(reproduce: dict[str, Any], *, task_path: Path) -> None:
    assert set(reproduce) == {"command_path"}
    assert isinstance(reproduce["command_path"], str) and reproduce["command_path"]
    if reproduce["command_path"] != "未自动推断":
        assert (task_path / reproduce["command_path"]).is_file()


def _assert_claim_traces(
    traces: list[dict[str, Any]],
    *,
    summary: dict[str, Any],
    expected_status: str,
) -> None:
    assert isinstance(traces, list)
    assert traces

    by_id = {item["claim_id"]: item for item in traces}
    for item in traces:
        assert {"claim_id", "surface", "claim_type", "value", "evidence"} <= set(item)
        assert item["surface"] == "report"
        assert isinstance(item["claim_id"], str) and item["claim_id"]
        assert isinstance(item["claim_type"], str) and item["claim_type"]
        assert isinstance(item["evidence"], list)
        assert item["evidence"]
        for evidence in item["evidence"]:
            _assert_claim_evidence(evidence)

    figures = summary["figures"]
    assert by_id["report.figures.count"]["claim_type"] == "figure_count"
    assert by_id["report.figures.count"]["value"] == figures["figure_count"]

    metrics = summary["metrics"]
    if metrics["present"]:
        assert "report.metrics.row_count" in by_id
        assert by_id["report.metrics.row_count"]["value"] == metrics["row_count"]
        assert "report.metrics.detected_fields" in by_id
        assert by_id["report.metrics.detected_fields"]["value"] == metrics["detected_fields"]

        for item in metrics["numeric_summaries"]:
            for operation in ["mean", "min", "max"]:
                claim_id = f"report.metric.{item['column']}.{operation}"
                assert claim_id in by_id
                assert by_id[claim_id]["claim_type"] == "numeric_summary"
                assert by_id[claim_id]["operation"] == operation
                assert by_id[claim_id]["field"] == item["column"]

        if metrics["numeric_omitted_count"] > 0:
            assert "report.metrics.numeric_fields_omitted" in by_id
            assert by_id["report.metrics.numeric_fields_omitted"]["value"] == metrics["numeric_omitted_count"]

        scenario = metrics["scenario"]
        if scenario["present"]:
            assert "report.metrics.scenario_summary" in by_id
            evidence = by_id["report.metrics.scenario_summary"]["evidence"]
            assert evidence[0]["artifact_id"] == "metrics_scenario_summary"
            assert evidence[0]["body"] == "omitted"
    else:
        assert "report.metrics.unavailable" in by_id
        assert by_id["report.metrics.unavailable"]["claim_type"] == "unknown_or_unavailable"
        assert not any(item["claim_type"] == "numeric_summary" for item in traces)

    if expected_status == "failed":
        assert "report.diagnostic.failed_status" in by_id
        assert by_id["report.diagnostic.failed_status"]["value"] == "failed"
    elif expected_status == "cancelled":
        assert "report.diagnostic.cancelled_status" in by_id
        assert by_id["report.diagnostic.cancelled_status"]["value"] == "cancelled"
    else:
        assert "report.diagnostic.failed_status" not in by_id
        assert "report.diagnostic.cancelled_status" not in by_id


def _assert_claim_evidence(evidence: dict[str, Any]) -> None:
    assert isinstance(evidence, dict)
    assert isinstance(evidence.get("artifact_id"), str) and evidence["artifact_id"]
    assert isinstance(evidence.get("path"), str) and evidence["path"]
    assert "rows" not in evidence
    if evidence["artifact_id"] in {"metrics_scenario_summary", "log_stderr"}:
        assert evidence["body"] == "omitted"
    elif "body" in evidence:
        assert evidence["body"] == "omitted"


def _assert_summary_is_reference_only(summary: dict[str, Any]) -> None:
    serialized = json.dumps(summary, ensure_ascii=False)
    for fragment in FORBIDDEN_EMBEDDED_FRAGMENTS:
        assert fragment not in serialized


def _is_bounded_scalar(value: Any) -> bool:
    if isinstance(value, str):
        return len(value) <= 160
    return value is None or isinstance(value, bool | int | float)


def _write_wide_metrics_csv(path: Path) -> None:
    headers = [
        "epoch",
        "model",
        "seed",
        "val_accuracy",
        "val_loss",
        *[f"metric_{index:02d}" for index in range(1, 11)],
        *[f"note_{index:02d}" for index in range(1, 11)],
    ]
    rows = [
        [
            "1",
            "wide-a",
            "1",
            "0.71",
            "0.52",
            *[str(index) for index in range(1, 11)],
            *[f"note-a-{index}" for index in range(1, 11)],
        ],
        [
            "2",
            "wide-a",
            "1",
            "0.82",
            "0.41",
            *[str(index + 1) for index in range(1, 11)],
            *[f"note-b-{index}" for index in range(1, 11)],
        ],
    ]
    text = "\n".join([",".join(headers), *(",".join(row) for row in rows)]) + "\n"
    path.write_text(text, encoding="utf-8")


def test_report_summary_completed_after_collect_and_figures_matches_public_contract(tmp_path: Path) -> None:
    workspace = tmp_path / "report-summary-contract-completed"
    workspace.mkdir()
    copy_examples(workspace)
    assert invoke(workspace, ["init"]).exit_code == 0

    task_id = extract_task_id(invoke(workspace, ["ingest", "examples/algorithm-benchmark/results.json"]).output)
    assert invoke(workspace, ["collect", task_id]).exit_code == 0
    assert invoke(workspace, ["figures", task_id]).exit_code == 0
    assert invoke(workspace, ["report", task_id]).exit_code == 0

    summary = read_report_summary(workspace, task_id)
    assert_report_summary_contract(
        summary,
        workspace=workspace,
        expected_task_id=task_id,
        expected_status="completed",
    )
    assert summary["figures"]["present"] is True
    assert summary["figures"]["figure_count"] > 0
    assert summary["metrics"]["scenario"]["present"] is True
    assert summary["metrics"]["scenario"]["seed_aggregates"]["present"] is True


def test_report_summary_completed_after_collect_without_figures_stays_bounded(tmp_path: Path) -> None:
    workspace = tmp_path / "report-summary-contract-no-figures"
    workspace.mkdir()
    _write_wide_metrics_csv(workspace / "wide_metrics.csv")
    assert invoke(workspace, ["init"]).exit_code == 0

    task_id = extract_task_id(invoke(workspace, ["ingest", "wide_metrics.csv"]).output)
    assert invoke(workspace, ["collect", task_id]).exit_code == 0
    assert invoke(workspace, ["report", task_id]).exit_code == 0

    summary = read_report_summary(workspace, task_id)
    assert_report_summary_contract(
        summary,
        workspace=workspace,
        expected_task_id=task_id,
        expected_status="completed",
    )
    assert summary["figures"]["present"] is False
    assert summary["metrics"]["present"] is True
    assert summary["metrics"]["omitted_column_count"] > 0
    assert summary["metrics"]["numeric_omitted_count"] > 0


def test_report_summary_failed_run_matches_public_contract(tmp_path: Path) -> None:
    workspace = tmp_path / "report-summary-contract-failed"
    workspace.mkdir()
    copy_examples(workspace)
    assert invoke(workspace, ["init"]).exit_code == 0

    command = f'"{sys.executable}" examples/simple-failure/fail.py'
    task_id = extract_task_id(invoke(workspace, ["run", command]).output)
    assert invoke(workspace, ["report", task_id]).exit_code == 0

    summary = read_report_summary(workspace, task_id)
    assert_report_summary_contract(
        summary,
        workspace=workspace,
        expected_task_id=task_id,
        expected_status="failed",
    )
    assert summary["metrics"]["present"] is False
    assert "FileNotFoundError" in summary["failure"]["failure_summary"]


def test_report_summary_cancelled_background_run_matches_public_contract(tmp_path: Path) -> None:
    workspace = tmp_path / "report-summary-contract-cancelled"
    workspace.mkdir()
    script = workspace / "cancel_me.py"
    script.write_text(
        "\n".join(
            [
                "import time",
                "print('report-summary-contract-ready', flush=True)",
                "time.sleep(30)",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    assert invoke(workspace, ["init"]).exit_code == 0

    command = f'"{sys.executable}" cancel_me.py'
    task_id = extract_task_id(invoke(workspace, ["run", command, "--background"]).output)
    wait_for_output(workspace, task_id, "report-summary-contract-ready")
    assert invoke(workspace, ["cancel", task_id]).exit_code == 0
    assert invoke(workspace, ["report", task_id]).exit_code == 0

    summary = read_report_summary(workspace, task_id)
    assert_report_summary_contract(
        summary,
        workspace=workspace,
        expected_task_id=task_id,
        expected_status="cancelled",
    )
    assert summary["metrics"]["present"] is False
    assert summary["cancellation"]["stderr_tail_line_count"] <= STDERR_TAIL_LINES
